---
version: 2
jobs:
  build:
    working_directory: ~/bunnyflat
    docker:
      - image: circleci/ruby:2.7.0-node
        environment:
          PGHOST: localhost
          PGUSER: bunnyflat
          RAILS_ENV: test
      - image: postgres:11.5
        environment:
          POSTGRES_USER: bunnyflat
          POSTGRES_DB: bunnyflat_test
          POSTGRES_PASSWORD: ""
    steps:
        - checkout

        - run: gem update bundler

        # Restore Cached Dependencies
        - type: cache-restore
          name: Restore bundle cache
          key: bunnyflat-{{ checksum "Gemfile.lock" }}

        # Bundle install dependencies
        - run: bundle install --path vendor/bundle

        # Cache Dependencies
        - type: cache-save
          name: Store bundle cache
          key: bunnyflat-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

        # Wait for DB
        - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
        - run: bundle exec rails db:setup

      # Run the tests
        - run: bundle exec rails test
